[tool.poetry]
name = "real time web app"
version = "0.1.0"
description = ""
authors = ["john zhang"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
dash = "^2.11.1"
dbt-postgres = "^1.6.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
